### ISSUE TITLE
Session destroy does not work

### ISSUE THREAD

**Issue by cvh23** [makepost/connect-typeorm#1]
# Bug

## Symptom
If one tries to destroy a session via `req.session.destroy()` the destroy method of TypeormStore is called. Within this method (`TypeormStore.ts`, line 106), there is a TypeORM call which does not work:
`TypeError: this.repository.deleteById is not a function`

## Solution
The TypeORM method is called "delete" so line 106 should be changed to:
`this.repository.delete(x)`
At least thats working for me.

PS: Is there a typo in `TypeormStore.ts` line 23 or what does the '!' stand for?

**Comment by binki** [comment]
It looks like [`deleteById` exists in typeorm-0.1](https://github.com/typeorm/typeorm/blob/0.1.19/src/repository/Repository.ts#L195). They removed it in 0.2.

It seems that `connect-typeorm` relies on a specific version of typeorm being used by the consuming package. I think that this is what [`peerDependency`](https://nodejs.org/en/blog/npm/peer-dependencies/) is for. It seems that it exists https://github.com/makepost/connect-typeorm/blob/c9a974314b4129e480d5116e6b4d1648011e3c15/package.json#L23 but that it purposefully claims to be compatible with 0.2 when it really isn’t. The suggested fix of moving to `this.repository.delete()` should be compatible with both 0.1 and 0.2, so that should probably be pursued.

I’m not sure how to make this more permanently fixed. In npm, 0.1 and 0.2 are considered MAJOR version differences (leading 0. is ignored when checking compatibility). So typeorm is allowed to make backwards-incompatible changes between those versions. It might be best/simplest to set the peer dependency to typeorm-0.2, remove 0.1, and update the devDependency to 0.2, and bump the major version of this library. That way, TypeScript will prevent this accident from happening again (like it’s supposed to).
